FROM node:18-alpine

RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app
COPY . .
ARG MONGO_URI
ARG AUTH_ORIGIN
ARG NAME
ARG SECRET
ARG MAIL_USER
ARG MAIL_PASSWORD
ARG smtpHost
ARG smtpPort
ARG smtpUser
ARG smtpPass
ARG PORT
ARG NUXT_HOST
ARG NUXT_PORT
ARG NEXTAUTH_URL
ARG PUBLIC_SITE_URL
ARG BOT_ID
ARG BOT_TOKEN
ARG BOT_LOGIN

ENV MONGO_URI=${MONGO_URI}
ENV SECRET=${SECRET}
ENV NAME=${NAME}
ENV PUBLIC_SITE_URL=${PUBLIC_SITE_URL}
ENV AUTH_ORIGIN=${AUTH_ORIGIN}
ENV MAIL_USER=${MAIL_USER}
ENV MAIL_PASSWORD=${MAIL_PASSWORD}
ENV smtpHost=${smtpHost}
ENV smtpPort=${smtpPort}
ENV smtpUser=${smtpUser}
ENV smtpPass=${smtpPass}
ENV PORT=${PORT}
ENV NUXT_HOST=${NUXT_HOST}
ENV NUXT_PORT=${NUXT_PORT}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV BOT_ID=${BOT_ID}
ENV BOT_TOKEN=${BOT_TOKEN}
ENV BOT_LOGIN=${BOT_LOGIN}


RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run build
ENV NODE_ENV production
ENV PORT 80

EXPOSE 80 

ENTRYPOINT ["node", ".output/server/index.mjs"]
